In [1]:
# The broadcast mechanism is used to handle operations between two arrays of
# different dimensions
import numpy as np
import pandas as pd

In [2]:
# scalar and an array perform operations
res = 3 * np.ones((2,2)) + 1
res

array([[4., 4.],
       [4., 4.]])

In [6]:
res = 1 / (res)


In [7]:
res

array([[0.25, 0.25],
       [0.25, 0.25]])

In [8]:
# computation between vector with matrix
# dot
# array.dot(array)
a = np.array([1,2,3])
b = np.array([1,3,5])
a.dot(b)

np.int64(22)

In [ ]:
# vector norm
exp_array = np.array([3,4])
np.linalg.norm(exp_array)

np.float64(5.0)

In [12]:
# in matrix norm, ord parameter is the most important
# ord:
# - None Frobenius norm
# - fro Frobenius norm
# - nuc nuclear norm
# - inf max(sum(abs(x)), axis=1)
matrix_target = np.arange(4).reshape(-1,2)
matrix_target

array([[0, 1],
       [2, 3]])

In [13]:
np.linalg.norm(matrix_target, 'fro')

np.float64(3.7416573867739413)

In [17]:
np.linalg.norm(matrix_target, 1)

np.float64(4.0)