In [1]:
import numpy as np
import pandas as pd

In [2]:
# transpose
# np.array.T
np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
np.empty((3,4)).T

array([[1.39340242e-311, 1.21190256e-305, 0.00000000e+000],
       [5.13241968e-305, 0.00000000e+000, 1.39338183e-311],
       [0.00000000e+000, 1.39338183e-311, 7.56745120e-307],
       [1.39340242e-311, 2.00485144e-307, 0.00000000e+000]])

In [4]:
# combination operation
# r_, c_
# usage: np.r_[np.array_1, np.array_2]
np.r_[np.zeros((2,3)), np.zeros((2,3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.array([0,0])

array([0, 0])

In [7]:
np.zeros(2)

array([0., 0.])

In [ ]:
# numpy.reshape
# Rearrange the array according to a new dimension, with two mode C and F
# C: Filled by row
# F: Filled by column
np.arange(8).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
np.arange(8).reshape((2,4), order='C')

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
np.arange(8).reshape((2,4),order='F')

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [18]:
# Since the dimensions of the array is confirmed, there can be a dimension empty, filled by -1
np.arange(9).reshape((3,-1), order='F')

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [19]:
# Transform n*1 array to one dimension array
np.zeros((3,1)).reshape(-1)

array([0., 0., 0.])

In [22]:
# slicing in numpy
target = np.arange(9).reshape(3,3)
target[:-1,[0,2]]

array([[0, 2],
       [3, 5]])

In [ ]:
# When two are both list (advanced index), pairwise matching
target[[0,1], [0,2]]

array([0, 5])

In [24]:
# utilize np.ix_ to boolean index on corresponding dimension
target[np.ix_([True, False, True], [True, False, True])]

array([[0, 2],
       [6, 8]])