In [2]:
import numpy as np
import pandas as pd

In [3]:
# transpose
# np.array.T
np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
np.empty((3,4)).T

array([[6.95289166e-310, 2.21210356e+214, 1.71130458e+059],
       [8.23900250e+015, 3.50849418e+016, 1.62980191e+045],
       [1.17316622e+079, 1.31531594e-047, 2.67108442e+098],
       [7.49229521e+247, 7.32845376e+025, 4.80511888e+257]])

In [6]:
# combination operation
# r_, c_
# usage: np.r_[np.array_1, np.array_2]
np.r_[np.zeros((2,3)), np.zeros((2,3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.array([0,0])

array([0, 0])

In [11]:
np.zeros(2)

array([0., 0.])