In [1]:
import numpy as np
import pandas as pd

In [2]:
# transpose
# np.array.T
np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
np.empty((3,4)).T

array([[1.35913080e-311, 1.35807731e-311, 9.99108793e-048],
       [2.81617418e-322, 5.74084271e+169, 3.93209153e-061],
       [0.00000000e+000, 4.22488031e-090, 6.48224660e+170],
       [0.00000000e+000, 3.34561262e-061, 4.93432906e+257]])

In [4]:
# combination operation
# r_, c_
# usage: np.r_[np.array_1, np.array_2]
np.r_[np.zeros((2,3)), np.zeros((2,3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.array([0,0])

array([0, 0])

In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
# numpy.reshape
# Rearrange the array according to a new dimension, with two mode C and F
# C: Filled by row
# F: Filled by column
np.arange(8).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
np.arange(8).reshape((2,4), order='C')

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
np.arange(8).reshape((2,4),order='F')

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [11]:
# Since the dimensions of the array is confirmed, there can be a dimension empty, filled by -1
np.arange(9).reshape((3,-1), order='F')

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [12]:
# Transform n*1 array to one dimension array
np.zeros((3,1)).reshape(-1)

array([0., 0., 0.])

In [13]:
# slicing in numpy
target = np.arange(9).reshape(3,3)
target[:-1,[0,2]]

array([[0, 2],
       [3, 5]])

In [14]:
# When two are both list (advanced index), pairwise matching
target[[0,1], [0,2]]

array([0, 5])

In [15]:
# utilize np.ix_ to boolean index on corresponding dimension
target[np.ix_([True, False, True], [True, False, True])]

array([[0, 2],
       [6, 8]])

In [17]:
# For arrays that contain missing values, to skip the missing values, you need to use
# nan* functions.
target = np.array([1, 2, np.nan, np.nan])

In [19]:
target.max()
np.nanmax(target)

np.float64(2.0)

In [21]:
np.nanmax(target)

np.float64(2.0)

In [22]:
np.nanquantile(target,0.5)

np.float64(1.5)

In [23]:
# for covirance and correlation
target1= np.array([1, 3, 5, 9])
target2 = np.array([1,5,3,-9])

In [24]:
# np.cov(array1, array2)
np.cov(target1, target2)

array([[ 11.66666667, -16.66666667],
       [-16.66666667,  38.66666667]])

In [25]:
np.corrcoef(target1, target2)

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

In [27]:
# For 2d array, statistic functions' aixs parameter means calculate the stat on a given dimension
# axis = 0 -> column
# aixs = 1 -> row
target = np.arange(1,10).reshape(3,-1)
target

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
target.sum(axis=0)

array([12, 15, 18])

In [29]:
target.sum(axis=1)

array([ 6, 15, 24])