In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
# Some numpy arrays generation methods np.linspace, np.arange
# Arithmetic sequence
# np.linspace(start, end(included), numbers of elements)
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [6]:
# np.arange(start, end(not included), stepsize)
np.arange(1, 6, 2)

array([1, 3, 5])

In [7]:
# special matrix generation
# zeros
# np.zeros((row, column))
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# identity matrix
# np.eye(dimension, k=0) k is the offset unit from the diagonal
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
# full matrix
# np.full((row, column), input values)
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
# random matrix
# most commonly used random number generate function: rand, randn, randint, choice
# They represent uniformly distributed random arrays from 0 to 1, 
# standard normal random arrays, random integer arrays, and random list sampling respectively:

# np.random.rand(rows, columns), generate 3 random numbers following a uniform distribution between 0 - 1
np.random.rand(3)

array([0.73106708, 0.23288332, 0.96030771])

In [13]:
# np.random.rand(rows, columns)
np.random.rand(3,3)

array([[0.5332011 , 0.75777739, 0.26125942],
       [0.18896357, 0.50668869, 0.60061709],
       [0.65003752, 0.04899824, 0.36028634]])

In [ ]:
# np.random.uniform(a, b, (rows, columns)) used for data points following uniform distribution between (a, b)
np.random.uniform(1,5,(3,3))

array([[1.09399282, 1.26985341, 3.82150391],
       [2.95618763, 3.63942649, 2.91029396],
       [1.40753257, 2.11906383, 1.51694359]])

In [16]:
# np.random.randn(rows, columns) generate numbers following standard normal distribution
np.random.randn(3)

array([ 3.3345173 ,  1.24279669, -0.44685829])

In [17]:
np.random.randn(2,2)

array([[ 0.41813541,  0.83892971],
       [-0.11623709, -1.67173662]])

In [18]:
# for the normal distribution following sigma^2 and mean μ
sigma, mu = 2.5, 3
mu + np.random.randn(3,3) * sigma

array([[ 4.18276051,  7.7923353 ,  7.9340435 ],
       [-0.9497097 ,  0.84310124,  1.12923439],
       [ 3.65011562,  3.11930256,  3.20753242]])

In [22]:
# or the existing function
# np.random.normal(mu, sigma, (rows, columns))
np.random.normal(3, 2.5, (10,10))

array([[-0.22651712,  4.56391005,  1.99979438,  2.08961119,  1.22376777,
        -2.95861831,  0.66171992,  1.725446  ,  3.44246606,  4.1881775 ],
       [ 8.68564045,  4.07975803,  3.11361452,  0.23327603,  0.79330684,
         6.83722916,  5.31843772,  2.90929199, -1.48525262,  4.71103148],
       [ 0.77388717,  6.03436589, -0.82737997,  5.86802132,  3.45675031,
         1.02951329,  2.00883075,  2.66831101, -0.52955867,  5.00420221],
       [ 3.30128883,  1.75238113,  4.16655533,  7.08285858,  1.4677267 ,
         3.4294358 ,  7.81976478,  2.89858286,  6.61826629,  4.36402358],
       [ 1.04199793,  5.2237447 ,  1.48396399,  2.34766358,  3.47375064,
         2.07858304, -0.60268796, -0.44304022,  2.75322673,  1.82303772],
       [ 7.0808569 ,  7.95027962,  7.10159018,  4.53413563,  2.65712957,
         5.64420622,  3.78813958,  1.51267107,  6.47674087,  4.0219472 ],
       [ 5.95885703,  5.01172826,  0.3447438 ,  3.61472225,  4.08507548,
         0.96473157, -0.2096447 ,  1.22588027

In [24]:
# np.random.randint can specify the generated integers' maximum(not included) and minimum, and dimensions
low, high, size = 5, 15, (2,2)
np.random.randint(low, high, size)

array([[ 5, 11],
       [ 7, 11]], dtype=int32)

In [27]:
#np.random.choice can randomly pick serveral elements from a given list by a given probability
# np.random.choice(list, dimensions, replace=False, p=[])
lst = [0.2 for _ in range(10)]
my_list = [1,2,3,4,5,6,7,8,9,10,11,12]
np.random.choice(my_list,(3,3),replace=True,p=[(1/len(my_list)) for _ in range(len(my_list))])

array([[ 1,  1,  7],
       [11,  1,  1],
       [ 8,  6, 11]])

In [30]:
np.random.choice(my_list, (3,3), replace=True, p=np.ones((len(my_list))) / len(my_list))

array([[ 5, 11,  1],
       [ 5,  1, 10],
       [11, 10,  5]])

In [31]:
# random seed
# can be used to fix the random number output result
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [33]:
np.random.seed(0)
np.random.rand()

0.5488135039273248