In [1]:
import numpy as np
import pandas as pd

In [4]:
# where
a = np.array([-1,1,-1,1])
np.where(a>0, a, 5)

array([5, 1, 5, 1])

In [5]:
# nonzero, argmax, argmin
# nonzero returns indexs of non-zero elements
# argmax returns index of biggest element
# argmin returns index of smallest element
a = np.array([-2, 3, 4, -5, 0, 1, 2])
np.nonzero(a)

(array([0, 1, 2, 3, 5, 6]),)

In [7]:
a.argmax()

np.int64(2)

In [8]:
a.argmin()

np.int64(3)

In [9]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a.argmin(axis=0)

array([0, 0, 0])

In [10]:
a.argmin(axis=1)

array([0, 0, 0])

In [11]:
# any, all, when array has at least one/ all True or nonzeron elements, return True, else False
a = np.array([0,1])
a.any()

np.True_

In [12]:
a.all()

np.False_

In [13]:
# cumprod, cumsum, diff
# cumprod, cumulative product np.cumprod()
a = np.array([1,2,3,4,5])
np.cumprod(a)

array([  1,   2,   6,  24, 120])

In [14]:
# cumsum, cumulative sum np.cumsum()
np.cumsum(a)

array([ 1,  3,  6, 10, 15])

In [15]:
# diff, denotes the difference between this element and the previous one
np.diff(a)

array([1, 1, 1, 1])

In [17]:
# Statistic functions
# max, min, mean, median, std, var, sum, quantile
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a.max()

np.int64(9)

In [19]:
# quantile np.quantile(array, quantile)
np.quantile(a, 0.5)

np.float64(4.5)